# Generated by Django 2.2.20 on 2021-05-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210521_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 5, 21, 13, 21, 27, 972158), verbose_name='Опубликована'),
        ),
    ]
