# Generated by Django 2.2.20 on 2021-05-21 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210521_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 5, 21, 13, 23, 35, 452675), verbose_name='Опубликована'),
        ),
    ]
